### ISSUE TITLE
Command timed out after no response trying to deploy hugo blog to github page with wercker

### ISSUE THREAD

**Issue by herveDarritchon** [lvivier/step-gh-pages#8]
I am trying to setup an automatic deployment of my Hugo blog to the Github Pages using Wercker. The build phase is ok, I can build my public directory with my blog static files. But I have a Command timed out after no response error while trying to deploy my hugo blog to the github page.

###This is my wercker.yml file
```
    box: python:wheezy
    no-response-timeout: 15
    build:
      steps:
        - arjen/hugo-build:
            theme: hd-theme
            flags: --disableSitemap=true
    deploy:
      steps:
        - lukevivier/gh-pages@0.2.1:
            token: $GIT_TOKEN
            repo: herveDarritchon/herveDarritchon.github.io
            basedir: public
    ```
    
    ### My log Error during deployment
   
    Running wercker version: 1.0.152 (Compiled at: 2015-06-02T19:21:14Z, Git commit: 12391582ed7323e803e15b277b9da3a65f7dde7c)
    Using config:
    box: python:wheezy
    no-response-timeout: 15
    build:
      steps:
        - arjen/hugo-build:
            theme: hd-theme
            flags: --disableSitemap=true
    deploy:
      steps:
        - lukevivier/gh-pages@0.2.1:
            token: $GIT_TOKEN
            repo: herveDarritchon/herveDarritchon.github.io
            basedir: public
    
    Pulling repository python
    Pulling image (wheezy) from python: 169d81d45993
    Pulling image (wheezy) from python, endpoint: https://registry-1.docker.io/v1/: 169d81d45993
    Pulling dependent layers: 169d81d45993
    Download complete: 7a3e804ed6c0
    Download complete: b96d1548a24e
    Download complete: 0f57835aec39
    Download complete: 7d22d0f990bc
    Download complete: be6ffc9d87fc
    Download complete: 6cb13f325b61
    Download complete: b394be4f3c52
    Download complete: ddc8488da9fa
    Download complete: 13700980fafa
    Download complete: 7f729a93d07e
    Download complete: 089f6d0ff231
    Download complete: 7c67244ee4eb
    Download complete: 169d81d45993
    Download complete: 169d81d45993
    Status: Image is up to date for python:wheezy
    export WERCKER="true"
    export WERCKER_ROOT="/pipeline/source"
    export WERCKER_SOURCE_DIR="/pipeline/source"
    export WERCKER_CACHE_DIR="/cache"
    export WERCKER_OUTPUT_DIR="/pipeline/output"
    export WERCKER_PIPELINE_DIR="/pipeline"
    export WERCKER_REPORT_DIR="/pipeline/report"
    export WERCKER_APPLICATION_ID="556eaec700bccd884305010b"
    export WERCKER_APPLICATION_NAME="software-the-good-parts"
    export WERCKER_APPLICATION_OWNER_NAME="herveDarritchon"
    export WERCKER_APPLICATION_URL="https://app.wercker.com/#application/556eaec700bccd884305010b"
    export TERM="xterm-256color"
    export DEPLOY="true"
    export WERCKER_DEPLOY_ID="556eced1453eb1bb0500347f"
    export WERCKER_DEPLOY_URL="https://app.wercker.com/#deploy/556eced1453eb1bb0500347f"
    export WERCKER_GIT_DOMAIN="github.com"
    export WERCKER_GIT_OWNER="herveDarritchon"
    export WERCKER_GIT_REPOSITORY="software-the-good-parts"
    export WERCKER_GIT_BRANCH="master"
    export WERCKER_GIT_COMMIT="9c247dfd78daa8897f4ef73cf050f6a72a35ffbb"
    export WERCKER_DEPLOYTARGET_NAME="software-the-good-part"
    export WERCKER_STARTED_BY="herveDarritchon"
    export WERCKER_MAIN_PIPELINE_STARTED="1433325265"

I have a timeout message, I tried to raised the time out duration in case but with 15mn I also run into the time out.

Any help appreciate,

Hervé

**Comment by herveDarritchon** [comment]
Hi,

I have fixed my problem.
It comes from my wercker.yml file and the content of the deply step.

```
    deploy:
      steps:
        - lukevivier/gh-pages@0.2.1:
            token: $GIT_TOKEN
            repo: herveDarritchon/herveDarritchon.github.io
            basedir: public
```

In fact, the *domain* tag is not optional, I have to set it up to github.com to have my deploy step to run.

I think you should change your documentation to be more straight forward for newbie ;)

Thanks anyway for this step.

**Comment by zj8487** [comment]
Hi,
I have the same problem, but it is not fixed by the follow config.
```
deploy:
    steps:
        - script:
            name: install git
            code: |
                sudo apt-get update
                sudo apt-get install git -y
        - lukevivier/gh-pages@0.2.1:
            token: $GIT_TOKEN
            domain: zj8487.com
            repo: zj8487/blog.zj8487.com
            basedir: public
```
